---
- name: Verify operating system
  ansible.builtin.assert:
    that: |
      {{ ntfy_installation_mode_package_supported_distros is contains(ansible_distribution) }}
    msg: Sorry, your platform is not supported at the momment.
  when: '"package" in ntfy_installation_mode'

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd if you enabled system support. See the Readme for more information."
  when: ntfy_system_systemd_used

- name: Verify Ansible meets version requirements
  block:
    - name: Check version of ansible package on the controller node
      ansible.builtin.shell: python3 -m pip show ansible | grep Version | cut -d ' ' -f 2
      changed_when: false
      register: _ansible_installed_version
      delegate_to: localhost
      run_once: true

    - name: Compare versions of installed ansible and required ansible
      ansible.builtin.assert:
        that: "_ansible_installed_version.stdout is version_compare(ansible_version_minimum, '>=')"
        msg: >
          "You must update Ansible to at least {{ ansible_version_minimum }} to use this role."
