---
- name: Do preparatory work
  ansible.builtin.include_tasks:
    file: preparation/main.yml
    apply:
      tags:
        - preparation_all
        - always  # can be slipped by '--skip-tags always' if needed for some reason
  tags:
    - preparation
    - always

- name: Install and configure ntfy
  ansible.builtin.include_tasks:
    file: ntfy/main.yml
    apply:
      tags: ntfy
  tags: ntfy
